var _cx = []; function _initCart() { var _s = localStorage.getItem('_cx_data'); if (_s) { try { _cx = JSON.parse(_s) } catch (e) { _cx = [] } } } _initCart();
function addToCart(pId) { var _p = _0xPROD.find(function (x) { return x.id === pId }); if (!_p) return; var _ex = _cx.find(function (x) { return x.id === pId }); if (_ex) { _ex.qty += 1; } else { var _e = { id: _p.id, n: _p.n, p: Number(_p.p), sp: _p.sp ? Number(_p.sp) : null, img: _p.img, qty: 1 }; _e.toJSON = function () { return { id: this.id, n: this.n, p: this.p, sp: this.sp, img: this.img, qty: this.qty } }; _cx.push(_e); } _saveCart(); _renderCart(); _updateBadge(); _showToast(_p.n + ' added to cart!'); setTimeout(_renderCart, 0) }
function removeFromCart(itemName) { for (var i = 0; i < _cx.length; i++) { if (_cx[i].n === itemName) { _cx.splice(i, 1); break } } _renderCart(); _updateBadge(); _saveCart() }
function updateQty(idx, delta) { if (idx >= 0 && idx < _cx.length) { _cx[idx].qty += delta; if (_cx[idx].qty <= 0) { _cx.splice(idx, 1); } _renderCart(); _updateBadge(); _saveCart() } }
function _calcTotal() { var t = 0; for (var i = 0; i < _cx.length; i++) { var _item = _cx[i]; var p = _item.sp || _item.p; t = t + p * _item.qty } return t.toFixed(2) }
function _calcItemCount() { var c = 0; for (var i = 0; i < _cx.length; i++) { c += _cx[i].qty; } return c; }
function _updateBadge() { var _b = document.querySelector('.cart-badge'); if (_b) { _b.textContent = _calcItemCount(); _b.style.display = _calcItemCount() > 0 ? 'flex' : 'none' } }
function _saveCart() { localStorage.setItem('_cx_data', JSON.stringify(_cx)) }
function _renderCart() { var _cEl = document.getElementById('cart-items'); var _tEl = document.getElementById('cart-total-value'); if (!_cEl || !_tEl) return; var _h = ''; for (var i = 0; i < _cx.length; i++) { var _it = _cx[i]; var p = _it.sp || _it.p; _h += '<div class="cart-item" data-idx="' + i + '">'; _h += '<img src="' + _it.img + '" alt="' + _it.n.replace(/"/g, '&quot;') + '" class="cart-item-img">'; _h += '<div class="cart-item-info">'; _h += '<h4 class="cart-item-name">' + _it.n + '</h4>'; _h += '<span class="cart-item-price">$' + p + '</span>'; _h += '<div class="cart-item-qty">'; _h += '<button aria-label="Decrease quantity" class="qty-btn qty-dec" onclick="updateQty(' + i + ',-1)">−</button>'; _h += '<span class="qty-val">' + _it.qty + '</span>'; _h += '<button aria-label="Increase quantity" class="qty-btn qty-inc" onclick="updateQty(' + i + ',1)">+</button>'; _h += '</div></div>'; _h += '<button aria-label="Remove item" class="cart-remove-btn" onclick="removeFromCart(\'' + _it.n.replace(/'/g, "\\'") + '\')">×</button>'; _h += '</div>' } _cEl.innerHTML = _h; _tEl.textContent = '$' + _calcTotal() }
function toggleCart() { var _s = document.getElementById('cart-sidebar'); var _o = document.getElementById('cart-overlay'); if (_s && _o) { _s.classList.toggle('open'); _o.classList.toggle('visible') } }
function _showToast(msg) { var _t = document.createElement('div'); _t.className = 'toast-notification'; _t.textContent = msg; document.body.appendChild(_t); setTimeout(function () { _t.classList.add('show') }, 10); setTimeout(function () { _t.classList.remove('show'); setTimeout(function () { _t.remove() }, 300) }, 2500) }
